sudo: required
services:
  - docker

before_install:
  - docker build -t jakasse/docker-react -f Dockerfile.dev .

script:
  - docker run jakasse/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Jak-Docker-react"
  env: "JakDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-982908300187"
  bucket_path: "Jak-Docker-react"
  on:
    branch: master
  access_key_id: "$aws_access_key_id"
  secret_access_key:
    secure: "$aws_secret_access_key"
